[workspace]

members = [
    "common-utils",
    "feathr-registry",
    "registry-provider",
    "atlas-provider",
    "sql-provider",
    "registry-api",
    "registry-cli",
    "raft-registry",
    "registry-app",
]

