name: Trigger auto deployment for feathrregistry

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/feathrregistry-AutoDeployTrigger-05614e69-d567-4aaa-be51-e57d8fa88d3e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.FEATHRREGISTRY_REGISTRY_USERNAME }}
          password: ${{ secrets.FEATHRREGISTRY_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: windoze/feathr-registry:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.FEATHRREGISTRY_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n feathrregistry -g xchfeathrtest4rg --server docker.io --username  ${{ secrets.FEATHRREGISTRY_REGISTRY_USERNAME }} --password ${{ secrets.FEATHRREGISTRY_REGISTRY_PASSWORD }}
            az containerapp update -n feathrregistry -g xchfeathrtest4rg --image windoze/feathr-registry:${{ github.sha }}
